services:
  backend:
    build:
      context: ./popoyan-backend
      dockerfile: Dockerfile.dev
    command: sh -c "npm run migrate && npm run dev"
    ports:
      - "3000:3000"
    env_file:
      - ./popoyan-backend/.env.docker
    volumes:
      - ./popoyan-backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./popoyan-frontend
      dockerfile: Dockerfile.dev
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./popoyan-frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=popoyan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d popoyan"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  pgdata: